version: '2.0'

services:

  zk:
    image: wurstmeister/zookeeper

  kafka08:
    image: wurstmeister/kafka:0.8.2.2
    expose:
      - 9092
    hostname: kafka08
    links:
      - zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka08
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "destination:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181

  kafka10:
    image: wurstmeister/kafka
    hostname: kafka10
    links:
      - zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka10
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "source:10:1"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk:2181

  relay:
    image: golang
    working_dir: "/opt/go/src/github.com/bculberson/kafka-relay"
    command: "go run main.go"
    links:
      - kafka08
      - kafka10
    environment:
      GOPATH: /opt/go/
      SOURCE: "kafka10:9092"
      SOURCE_TOPIC: "source"
      SOURCE_KEY_FIELD: "id"
      DESTINATION: "kafka08:9092"
      DESTINATION_TOPIC: "destination"
      DESTINATION_PARTITIONS: "1"
    volumes:
      - ".:/opt/go/src/github.com/bculberson/kafka-relay:rw"
